# Project Information
site_name: Notes/Tiankai Ma
site_description: "Tiankai Ma's Notes"
site_author: "Tiankai Ma"
site_url: https://notes.tiankaima.dev
strict: false

# Repository
repo_name: "tiankaima/md-notes"
repo_url: "https://github.com/tiankaima/md-notes"
edit_uri: https://github.com/tiankaima/md-notes/edit/main/docs/

# Copyright
copyright: "Copyright &copy; Tiankai Ma"

# Contents
nav:
  - Welcome:
      - Welcome [EN]: index.md
      - About [EN]: index/about.md
      - Test Page: index/test.md
  - Blog:
      - C++:
          - blog/cpp/modern-cpp.md
      - Python:
          - Package Management [EN]: blog/python/packages.md
      - Server:
          - blog/server/headscale.md
          - blog/server/rpi-setup.md
      - Typst:
          - blog/typst/typst-tutorial-for-latex-user.md
      - Terminal:
          - blog/terminal/cheatsheets.md
      - USTC:
          - blog/ustc/schoolwork-links.md
          - blog/ustc/ustc-websites.md
          - blog/ustc/xzkd-new-tokens.md
  - Math:
      - math/index.md
      - Analysis:
          - math/analysis/calculus.md
          - math/analysis/fourier.md
          - math/analysis/functional-analysis.md
          - math/analysis/measure-theory.md
          - math/analysis/attention-is-all-you-need.md
          - math/analysis/calculus-of-variations.md
      - Probability:
          - math/probability/probability.md
          - math/probability/stochastic-processes.md
  - Machine Learning:
      - ml/index.md
      - Traditional Methods:
          - Linear Regression: ml/traditional/linear-regression.md
          - Logistic Regression: ml/traditional/logistic-regression.md
      - Deep Learning:
          - Review: ml/dl/review.md
          - Neural Network:
              - ml/dl/nn/index.md
              - Backward Propagation: ml/dl/nn/bp.md
              - Playground/MNIST: ml/dl/nn/playground-mnist.ipynb
              - Miscellaneous:
                  - Derivative: ml/dl/nn/derivative.md
                  - Graph: ml/dl/nn/graph.ipynb
          - CNN:
              - ml/dl/cnn/index.md
              - History: ml/dl/cnn/history.md
              - Playground/LeNet: ml/dl/cnn/playground-lenet.ipynb
          - NeRF:
              - ml/dl/nerf/index.md
          - Gaussian Splatting:
              - ml/dl/gs/index.md
              - 3D Gaussian Splatting: ml/dl/gs/3d-gs.md
  - Lab:
      - lab/tutorial.md
      - Admin:
        - lab/admin/checklist.md
        - lab/admin/network.md
        - lab/admin/upgrading.md
      - Cluster 1:
          - lab/cls1/index.md
          - lab/cls1/srv2.md
      - Cluster 2:
          - lab/cls2/index.md

# Theme
theme:
  name: material
  static_templates:
    - 404.html
  language: "zh"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: "favicon.ico"
  icon:
    annotation: material/arrow-right-circle
    logo: "material/school"
  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.expand
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  font:
    text: "Fira Sans"
    code: "Fira Mono"

plugins:
  - search
  - git-revision-date-localized
  - glightbox
  - mkdocs-jupyter
  - redirects:
      redirect_maps:
        "blog/xzkd-new-tokens.md": "blog/ustc/xzkd-new-tokens.md"
        "blog/terminal/rpi-setup.md": "blog/server/rpi-setup.md"

# Customization
extra:
  disqus: "Tiankai Ma"
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>'
  pagetime: "on"
  manifest: "manifest.webmanifest"
  githash: ""

extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"
  - javascripts/svg_dark.js

extra_css:
  - css/extra.css
  - "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"

# Extensions
markdown_extensions:
  - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - markdown.extensions.def_list
  - md_in_html
  - toc:
      permalink: true
