# Project Information
site_name: Notes/Tiankai Ma
site_description: "Tiankai Ma's Notes"
site_author: "Tiankai Ma"
site_url: https://notes.tiankaima.dev
strict: false

# Repository
repo_name: "tiankaima/md-notes"
repo_url: "https://github.com/tiankaima/md-notes"

# Copyright
copyright: "Copyright &copy; Tiankai Ma"

# Contents
nav:
  - Welcome:
      - Welcome [EN]: index.md
      - About [EN]: index/about.md
      - Test Page: index/test.md
  - Blog:
      - blog/modern-cpp.md
      - blog/schoolwork-links.md
      - blog/typst-tutorial-for-latex-user.md
      - blog/ustc-websites.md
      - blog/xzkd-new-tokens.md
  - Math:
      - math/index.md
      - Analysis:
          - math/analysis/calculus.md
      - Probability:
          - math/probability/probability.md
          - math/probability/stochastic-processes.md
  - Machine Learning:
      - ml/index.md
      - Deep Learning:
          - ml/dl/index.md
          - Neural Networks:
              - ml/dl/nn/index.md
              - ml/dl/nn/derivative.md
          - ml/dl/cnn.md

# Theme
theme:
  name: null
  custom_dir: "mkdocs-material/material/templates"
  static_templates:
    - 404.html
  language: "zh"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: "favicon.ico"
  icon:
    annotation: material/arrow-right-circle
    logo: "material/school"
  features:
    - content.action.edit
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
  font:
    text: "Fira Sans"
    code: "Fira Mono"

plugins:
  - git-revision-date-localized
  - glightbox

# Customization
extra:
  disqus: "Tiankai Ma"
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>'
  pagetime: "on"
  manifest: "manifest.webmanifest"
  githash: ""

extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"

extra_css:
  - "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"

# Extensions
markdown_extensions:
  - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - markdown.extensions.def_list
  - md_in_html
  - toc:
      permalink: true
